import Head from "next/head";
import Link from 'next/link'
import Featured from "../components/HomePage/Featured";
import WhyChooseUS from "../components/HomePage/WhyChooseUS";
import Capabilities from "../components/HomePage/Capabilities";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>MADTechET - Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="mt-30">
        <div className="max-w-[1350px] px-6 mx-auto grid grid-cols-3 md:grid-cols-2 items-center h-screen-0.95 pt-40 ">
          <div className="col-span-2 md:col-span-1 md:pr-14 xl:pr-20 2xl:pr-36">
            <h1 className="text-2xl md:text-4xl font-semibold">
              <span className="block">DIGITAL </span>
              <span className="block">TRANSFORMATION</span>
            </h1>
            <p className="mt-8  text-textSecondary leading-7 text-lg">
              Based in Addis Ababa,Ethiopia we work Entrepreneurs, SMEs and
              large organizations globally to build their digital presence,
              expand their reach and grow their businesses.
            </p>
            <Link href="/our-works">
              <div className="btn-blue mt-5 hover:bg-sky-700 cursor-pointer">
                Our Works
              </div>
            </Link>
          </div>
        </div>
      </div>

      {/* Why choose us? */}
      <WhyChooseUS />

      {/* Capablities */}
      <Capabilities />

      {/* Featured */}
      <Featured />

   
    </div>
  );
}
